sonar.projectKey=EzCommerce-Backend
sonar.projectName=EzCommerce-Backend
sonar.projectVersion=1.0
sonar.sources=.

# Exclusiones corregidas con sintaxis Ant válida
sonar.exclusions=\
  **/migrations/**,\
  **/__pycache__/**,\
  **/tests/**,\
  **/urls.py,\
  **/swagger.py,\
  **/admin.py,\
  **/seed_data.py,\
  **/wsgi.py,\
  **/asgi.py,\
  **/test_settings.py,\
  **/__init__.py,\
  **/epica1/models.py,\
  manage.py,\
  run_sonar.py,\
  run_pytest.py,\
  Readme.md,\
  pytest.ini,\
  setup.cfg,\
  requirements.txt,\
  .gitignore,\
  .env*

sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000